name: Laravel Test

on:
  push:
    branches:
      - main
      - development


jobs:
  app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Docker network
        run: docker network create yosuite-network

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Run database migrations
        run: docker-compose run --rm -u root app php artisan migrate --force

      - name: Run seeder
        run: docker-compose run --rm -u root app php artisan db:seed --force

      - name: Run tests
        run: docker-compose run --rm -u root app vendor/bin/phpunit

      - name: Stop Docker Compose
        run: docker-compose down
