name: Laravel Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Docker network
        run: docker network create yosuite-network

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Run database migrations
        run: docker-compose run --rm  app php artisan migrate

      - name: Run seeder
        run: docker-compose run --rm  app php artisan db:seed

      - name: Run tests
        run: docker-compose run --rm  app vendor/bin/phpunit

      - name: Stop Docker Compose
        run: docker-compose down
